baseURL = 'https://thessy-travels.pages.dev/'
languageCode = 'en-us'
title = 'Smart Travel & Style'
theme = ["github.com/adityatelange/hugo-PaperMod"]
[params]
    env = "production"
    title = "Smart Travel & Style"
    description = "Your guide to Jumia deals and Travelstart adventures."
    author = "Admin"

    [params.homeInfoParams]
        Title = "Welcome to Smart Travel & Style ðŸ‘‹"
        Content = "We help you find the best retail deals and cheapest flights."

   [menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Gear Reviews"      # Great for your Jumia affiliate links
    url = "/posts/"
    weight = 20
  [[menu.main]]
    name = "Travel Tips"       # Guides on how to travel better/cheaper
    url = "/tips/"
    weight = 30
  [[menu.main]]
    name = "About Us"
    url = "/about/"
    weight = 40
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 50
